unified_checkpoint_v2/unified_checkpoint_v2/Controllers/AgenteController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using unified_checkpoint_v2.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.IO;
using ClosedXML.Excel;
using unified_checkpoint_v2.Negocio;

namespace unified_checkpoint_v2.Controllers
{
    public class AgenteController : Controller
    {
        DBUnifiedCheckpointEntities2 model = new DBUnifiedCheckpointEntities2();

        List<Agente> _agentes = new List<Agente>();

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            using (model)
            {
                var agentes = (from x in model.Agentes select x).ToList();

                return View(agentes);
            }
        }

        [HttpGet]
        public ActionResult InsertarAgente()
        {
            return View();
        }

        [HttpPost]
        public ActionResult InsertarAgente(Agente agente)
        {
            Auditoria auditoria = new Auditoria();
            AuditoriaHelpers auditoriaHelpers = new AuditoriaHelpers();
            try
            {
                AgenteHelpers agenteHelpers = new AgenteHelpers();
                agenteHelpers.sp_InsertarAgente(agente);

                using (model)
                {
                    var userId = User.Identity.GetUserId();
                    var usuarioAuditoria = (from x in model.AspNetUsers where x.Id == userId select x).FirstOrDefault();
                    auditoria.Usuario = userId; 
                    auditoria.Modulo = "Agentes";
                    auditoria.Accion = "El usuario " + usuarioAuditoria.UserName + " insertó el nuevo agente " + agente.Nombre + " " + agente.Apellido;
                }

                auditoriaHelpers.spAuditoria(auditoria);

                string mensaje = "Agente agregado corectamente!!";
                return Json(mensaje, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ex.ToString();
                string mensaje = "Error al ingresar este agente, por favor verifique que los campos sean correctos!!";
                return Json(mensaje, JsonRequestBehavior.DenyGet);
            }
        }

        [HttpGet]
        public ActionResult ActualizarAgente(int? cedula)
        {
            try
            {
                var getAgente = new Agente();
                getAgente = (from age in model.Agentes
                             where age.Cedula == cedula
                             select age).FirstOrDefault();
                return View(getAgente);
                //return Json(getAgente, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                ex.ToString();
                //return RedirectToAction("index", "Home");
                return Json(null, JsonRequestBehavior.DenyGet);
            }
        }

        [HttpPost]
        public ActionResult ActualizarAgente(Agente agente)
        {
            try
            {
                AgenteHelpers agenteHelpers = new AgenteHelpers();
                agenteHelpers.sp_ActualizarAgente(agente);

                Auditoria auditoria = new Auditoria();
                AuditoriaHelpers auditoriaHelpers = new AuditoriaHelpers();

                using (model)
                {
                    var userId = User.Identity.GetUserId();
                    var usuarioAuditoria = (from x in model.AspNetUsers where x.Id == userId select x).FirstOrDefault();
                    auditoria.Usuario = userId; 
                    auditoria.Modulo = "Agentes";
                    auditoria.Accion = "El usuario " + usuarioAuditoria.UserName + " actualizó el agente " + agente.Nombre + " " + agente.Apellido;
                }
                auditoriaHelpers.spAuditoria(auditoria);

                string mensaje = "Agente actualizado corectamente!!";
                return Json(mensaje, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ex.ToString();
                string mensaje = "Error al actualizar este agente, por favor verifique que los campos sean correctos!!";
                return Json(mensaje, JsonRequestBehavior.DenyGet);
            }
        }

        [HttpGet]
        public ActionResult EliminarAgente(int? cedula)
        {
            try
            {
                var getAgente = new Agente();
                getAgente = (from age in model.Agentes
                             where age.Cedula == cedula
                             select age).FirstOrDefault();
                return View(getAgente);

            }
            catch (Exception ex)
            {
                ex.ToString();
                //return RedirectToAction("index", "Home");
                return Json(null, JsonRequestBehavior.DenyGet);
            }
        }

        [HttpPost]
        public ActionResult EliminarAgente(Agente agente)
        {
            try
            {
                AgenteHelpers agenteHelpers = new AgenteHelpers();
                agenteHelpers.sp_EliminarAgente(agente);

                Auditoria auditoria = new Auditoria();
                AuditoriaHelpers auditoriaHelpers = new AuditoriaHelpers();

                using (model)
                {
                    var userId = User.Identity.GetUserId();
                    var usuarioAuditoria = (from x in model.AspNetUsers where x.Id == userId select x).FirstOrDefault();
                    auditoria.Usuario = userId;
                    auditoria.Modulo = "Agentes";
                    auditoria.Accion = "El usuario " + usuarioAuditoria.UserName + " eliminó el agente " + agente.Nombre + " "+ agente.Apellido;
                }
                auditoriaHelpers.spAuditoria(auditoria);

                string mensaje = "Agente eliminado corectamente!!";
                return Json(mensaje, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ex.ToString();
                string mensaje = "Error al eliminar este agente, por favor verifique que los campos sean correctos!!";
                return Json(mensaje, JsonRequestBehavior.DenyGet);
            }
        }

        [HttpGet]
        public ActionResult DetallesAgente(int? cedula)
        {
            try
            {
                var getAgente = new Agente();
                getAgente = (from age in model.Agentes
                             where age.Cedula == cedula
                             select age).FirstOrDefault();
                return View(getAgente);

            }
            catch (Exception ex)
            {
                ex.ToString();
                //return RedirectToAction("index", "Home");
                return Json(null, JsonRequestBehavior.DenyGet);
            }
        }

        public void CargarListaAgentes()
        {
            using (model)
            {
                var agente = (from x in model.Agentes select x).ToList();
                foreach (var item in agente)
                {
                    _agentes.Add(new Agente
                    {
                        TipoCedula = item.TipoCedula,
                        Cedula = item.Cedula,
                        Nombre = item.Nombre,
                        Apellido = item.Apellido,
                        Telefono = item.Telefono,
                        Correo = item.Correo,
                        Agencia = item.Agencia,
                        InformacionAdicional = item.InformacionAdicional
                    });
                }
            }
        }

        public ActionResult ExportarExcel()
        {
            CargarListaAgentes();
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Agentes");
                worksheet.ColumnWidth = 20;
                var currentRow = 1;

                //Header del Excel
                worksheet.Cell(currentRow, 1).Value = "Tipo de Cédula";
                worksheet.Cell(currentRow, 2).Value = "Cédula";
                worksheet.Cell(currentRow, 3).Value = "Nombre";
                worksheet.Cell(currentRow, 4).Value = "Apellidos";
                worksheet.Cell(currentRow, 5).Value = "Correo";
                worksheet.Cell(currentRow, 6).Value = "Agencia";
                worksheet.Cell(currentRow, 7).Value = "Información Adicional";

                //Body del Excel
                foreach (var item in _agentes)
                {
                    currentRow++;
                    worksheet.Cell(currentRow, 1).Value = item.TipoCedula;
                    worksheet.Cell(currentRow, 2).Value = item.Cedula;
                    worksheet.Cell(currentRow, 3).Value = item.Nombre;
                    worksheet.Cell(currentRow, 4).Value = item.Apellido;
                    worksheet.Cell(currentRow, 5).Value = item.Correo;
                    worksheet.Cell(currentRow, 6).Value = item.Agencia;
                    worksheet.Cell(currentRow, 7).Value = item.InformacionAdicional;
                }

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();


                    return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Agentes.xlsx");
                }
            }
        }
    }
}

unified_checkpoint_v2/unified_checkpoint_v2/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using unified_checkpoint_v2.Models;

namespace unified_checkpoint_v2.Controllers
{
    public class EventController : Controller
    {
        [Authorize(Roles = "Admin,Vendedor")]
        // GET: Event
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetEvents()
        {
            using (DBUnifiedCheckpointEntities2 dc = new DBUnifiedCheckpointEntities2())
            {
                var events = dc.Events.ToList();
                return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }

        [HttpPost]
        public JsonResult SaveEvent(Event e)
        {
            var status = false;
            using (DBUnifiedCheckpointEntities2 dc = new DBUnifiedCheckpointEntities2())
            {
                if (e.EventID > 0)
                {
                    //Update the event
                    var v = dc.Events.Where(a => a.EventID == e.EventID).FirstOrDefault();
                    if (v != null)
                    {
                        v.Subject = e.Subject;
                        v.Start = e.Start;
                        v.End = e.End;
                        v.Description = e.Description;
                    }
                }
                else
                {
                    dc.Events.Add(e);
                }

                dc.SaveChanges();
                status = true;

            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpPost]
        public JsonResult DeleteEvent(int eventID)
        {
            var status = false;
            using (DBUnifiedCheckpointEntities2 dc = new DBUnifiedCheckpointEntities2())
            {
                var v = dc.Events.Where(a => a.EventID == eventID).FirstOrDefault();
                if (v != null)
                {
                    dc.Events.Remove(v);
                    dc.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }
    }
}

unified_checkpoint_v2/unified_checkpoint_v2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Starter</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/adminlte/css/site.css" rel="stylesheet" />
    <link href="~/adminlte/plugins/jquery-ui/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/plugins/sweetalert2.css" rel="stylesheet" />
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/adminlte/img/logo_transparent.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Unified Checkpoint</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="info">
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                        <li class="nav-item menu-open">
                            <a href="#" class="nav-link active">
                                <i class="nav-icon fas fa-house-damage"></i>
                                <p>
                                    Gutiérrez Real Estate
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="@Url.Action("Index", "Event")" class="nav-link">
                                        <i class="fa fa-calendar nav-icon"></i>
                                        <p>Calendario</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("index", "Propietarios")" class="nav-link">
                                        <i class="fa fa-users nav-icon"></i>
                                        <p>Propietarios</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("index", "Propiedadess")" class="nav-link">
                                        <i class="fa fa-building nav-icon"></i>
                                        <p>Propiedades</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("index", "Cliente")" class="nav-link">
                                        <i class="fa fa-handshake nav-ico"></i>
                                        <p>Clientes</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("index", "Presupuesto")" class="nav-link">
                                        <i class="fas fa-donate nav-icon"></i>
                                        <p>Presupuestos</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Index", "Estadistica")" class="nav-link">
                                        <i class="fa fa-percent nav-icon"></i>
                                        <p>Estadisticas</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Register", "Account")" class="nav-link">
                                        <i class="fas fa-cogs nav-icon"></i>
                                        <p>Usuarios</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item menu-open">
                            <a href="#" class="nav-link active">
                                <i class="nav-icon fas fa-address-card"></i>
                                <p>
                                    Agentes
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="@Url.Action("index", "Agente")" class="nav-link">
                                        <i class="fa fa-briefcase nav-icon"></i>
                                        <p>Agentes</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("index", "PropiedadesAgente")" class="nav-link">
                                        <i class="fa fa-building nav-icon"></i>
                                        <p>Propiedades Agentes</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">@ViewBag.Title</h1>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->

    <script src="~/adminlte/js/jquery.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/adminlte/js")
    @RenderSection("scripts", required: false)
    <script src="~/adminlte/js/fechas.js"></script>
    <script src="~/adminlte/js/mantenimientos.js"></script>
    <script src="~/adminlte/js/selecciones.js"></script>
    <script src="~/adminlte/js/site.js"></script>
    <script src="~/adminlte/js/jquery-ui.js"></script>
</body>
</html>